GET http://localhost:4000/users
###

GET http://localhost:4000/users/j.nayon123@gmail.com
###

POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "testing",
    "password": "testing nasad",
    "email": "j.nayon123@gmail.com",
    "phone": "09267288567"
}
###
DELETE http://localhost:4000/users/660ca489e3d5f88ccc4d7d9c

###
PATCH http://localhost:4000/users/660ca4b2e3d5f88ccc4d7db2
Content-Type: application/json

{
    "name": "testing2",
    "email": "j.nayon123@gmail.com",
    "password": "testing nasad",
    "phone": "09267288567"
}


###
PATCH http://localhost:4000/users/j.nayon123@gmail.com/school
Content-Type: application/json

{
    "name": "Jaclupan ES"
}