GET http://localhost:4000/users
###

GET http://localhost:4000/users/j.nayon1221@gmail.com
###

POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "testing",
    "password": "testing nasad",
    "email": "j.nayon1221@gmail.com",
    "phone": "09267288567",
    "hello": "mane"
}
###
DELETE http://localhost:4000/users/660c2060c31e99a0c5484c3a

###
PATCH http://localhost:4000/users/j.nayon1221@gmail.com/school
Content-Type: application/json

{
    "name": "Jaclupan ES"
}