POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "testing2",
    "password": "testing nasad",
    "email": "j.nayon123@gmail.com",
    "phone": "09267288567"
}

###
GET http://localhost:4000/users/schools

###
GET http://localhost:4000/schools

###
POST http://localhost:4000/schools
Content-Type: application/json

{
    "name": "Tisa ES"
}