GET http://localhost:4000/users
###
DELETE http://localhost:4000/users/660b7c301e74ee8b63b557de

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "testing2",
    "password": "testing nasad",
    "email": "j.nayon123@gmail.com",
    "phone": "09267288567"
}

###
GET http://localhost:4000/users/schools