### Gets all the Associations
GET http://localhost:4000/associations

### Gets an Association by ID
GET http://localhost:4000/associations/662d5ae820a752475b6188f6s

### Create an association between User and School /invite and /apply
POST http://localhost:4000/associations/user/school/apply
Content-Type: application/json

{
    "user_id": "662d64b6a92ce851c3a291e9",
    "school_id": "6629798e05999fbb5ea6764d"
}

### Deletes an Association with the specified ID
DELETE http://localhost:4000/associations/662d65b31d955d0d1998face

### Patches the approved and admin properties of an Association
PATCH http://localhost:4000/associations/662d66114f0ccac941049ebf
Content-Type: application/json

{
    "approved": true,
    "admin": true
}