### Gets all the Associations
GET http://localhost:4000/associations

### Gets an Association by ID
GET http://localhost:4000/associations/66245ead3434b9414a6f4367

### Create an association between User and School
//Invitation = true, User applies to School
//Invitation = false, School invites User (default)
POST http://localhost:4000/associations/user/school
Content-Type: application/json

{
    "user_id": "66243a650fee83b088313546",
    "school_id": "661f31c70260a2d33a970464",
    "invitation": true
}

### Deletes an Association with the specified ID
DELETE http://localhost:4000/associations/66245e9e3434b9414a6f435e

### Patches the approved and admin properties of an Association
PATCH http://localhost:4000/associations/66245ead3434b9414a6f4367
Content-Type: application/json

{
    "approved": true,
    "admin": true
}