GET http://localhost:4000/associations

### CASE SENSITIVE
GET http://localhost:4000/associations/Principal

###
POST http://localhost:4000/positions
Content-Type: application/json

{
    "name": "ADOF"
}

###
DELETE http://localhost:4000/associations/661f33ee644b88d41c07e0dc

###
PATCH http://localhost:4000/associations/6618ba1dcd4848227911dd7f
Content-Type: application/json

{
    "name": "ADOF"
}