### By default naka ascending dapat /documents/lr/schools/{year}/{month}
GET http://localhost:4000/documents/jev/schools/2024/April
Content-Type: application/json

{
    "school_id": "661f31c70260a2d33a970464"
}

### By default naka ascending dapat /documents/lr/schools/{year}/{month}/{keyword}
GET http://localhost:4000/documents/lr/schools/2024/April/test
Content-Type: application/json

{
    "school_id": "661f31c70260a2d33a970464"
}

### Dashboard: Gets the sum of all documents and necessary proprties
GET http://localhost:4000/documents/schools/2024/April
Content-Type: application/json

{
    "school_id": "661f31c70260a2d33a970464"
}

### Creates a Document under a specified School, Year, and Month (required fields)
// The rest of the fields/properties are optional
POST http://localhost:4000/documents
Content-Type: application/json

{
    "school_id": "661f31c70260a2d33a970464",
    "month": "February",
    "year": "2024",
    "budget": 2000,
    "budget_limit": 400,
    "cash_advance": 10000,
    "sds": "ADOF",
    "claimant": "ADOF",
    "head_accounting": "ADOF"
}

### Deletes a Document by its specified ID
DELETE http://localhost:4000/documents/662fdcc944ae2d36597fcf32

### Updates a Document by its ID
// Fields that can be updated: budget, budget_limit, budget_exceeded, sds, claimant, head_accounting
PATCH http://localhost:4000/documents/662fdcc944ae2d36597fcf32
Content-Type: application/json

{
    "budget_limit": 700
}
