GET http://localhost:4000/jev

### Initialized the JEV and inserts the template records
POST http://localhost:4000/jev/initialize
Content-Type: application/json

{
    "doc_id": "662620cf8ab30c2f2cb3e24b"
}

###
POST http://localhost:4000/jev
Content-Type: application/json

{
    "doc_id": "662620cf8ab30c2f2cb3e24b",
    "respo_center": "test", 
    "account_explanation": "test", 
    "uacs_obj_code": "5029904000", 
    "debit": 0, 
    "credit": 200
}

###
DELETE http://localhost:4000/jev/66256a3d85170adeafa31c6b

###
DELETE http://localhost:4000/jev/document/662620cf8ab30c2f2cb3e24b

###
PATCH http://localhost:4000/jev/662568cdaa4772a2f2556cb3
Content-Type: application/json

{
    "credit":300
}