GET http://localhost:4000/jevs

###
POST http://localhost:4000/jevs
Content-Type: application/json

{
    "doc_id": "662567cdceed3e8f95b08bc0",
    "respo_center": "test", 
    "account_explanation": "test", 
    "uacs_obj_code": "test", 
    "debit": 0, 
    "credit": 200, 
    "prepared_by": "test", 
    "certified_cor": "test"
}

###
DELETE http://localhost:4000/jevs/66256a3d85170adeafa31c6b

###
PATCH http://localhost:4000/jevs/662568cdaa4772a2f2556cb3
Content-Type: application/json

{
    "credit":300
}