GET http://localhost:4000/lrs

###
POST http://localhost:4000/lrs
Content-Type: application/json

{
    "date": "test2",
    "ors_burs_no": "test2",
    "particulars": "test2",
    "amount":560
}

###
DELETE http://localhost:4000/lrs/6621deb64db421656fc6502d

###
PATCH http://localhost:4000/lrs/6621dfc2595f3fb723ceb73a
Content-Type: application/json

{
    "date": "test21",
    "ors_burs_no": "test2",
    "particulars": "test2",
    "amount":5604
}