GET http://localhost:4000/lrs

###
POST http://localhost:4000/lrs
Content-Type: application/json

{
    "doc_id": "662620cf8ab30c2f2cb3e24b",
    "date": "test4",
    "ors_burs_no": "test4",
    "particulars": "test4",
    "amount": 69.69,
    "payee": "gaisano",
    "uacs_obj_code": "1990101000",
    "nature_of_payment": "cash"
}

###
DELETE http://localhost:4000/lrs/6624f654ad59e1b645455d96

###
PATCH http://localhost:4000/lrs/6624f2072997e9b054e26b9b
Content-Type: application/json

{
    "amount":200
}