### Gets all the Notifications in the Database
GET http://localhost:4000/notifications

### Creates a notification using: user_id, assoc_id (optional), and details
POST http://localhost:4000/notifications
Content-Type: application/json

{
    "user_id": "66243a650fee83b088313546",
    "details": "Testing details"
}

### Deletes a Single Notification
DELETE http://localhost:4000/notifications/6624434af31ef28a942c8367

### Deletes a Single Notification
DELETE http://localhost:4000/notifications/all/users/66243a650fee83b088313546

### Patches the details and isRead properties of a Notification
PATCH http://localhost:4000/notifications/662443cef31ef28a942c837c
Content-Type: application/json

{
    "details": "ADOF",
    "isRead": true
}