GET http://localhost:4000/positions

### CASE SENSITIVE
GET http://localhost:4000/positions/Principal

###
POST http://localhost:4000/positions
Content-Type: application/json

{
    "name": "ADOF"
}

###
DELETE http://localhost:4000/positions/6618b9a72c2af3cb6d27d87b

###
PATCH http://localhost:4000/positions/6618ba1dcd4848227911dd7f
Content-Type: application/json

{
    "name": "ADOF"
}