GET http://localhost:4000/positions

### CASE SENSITIVE
GET http://localhost:4000/positions/Principals

###
POST http://localhost:4000/positions
Content-Type: application/json

{
    "name": "Accountant"
}

###
DELETE http://localhost:4000/positions/662ae06417d6ec13b7903bb0

###
PATCH http://localhost:4000/positions/662ae06417d6ec13b7903bb0
Content-Type: application/json

{
    "name": "Broker"
}