GET http://localhost:4000/rcds

###
POST http://localhost:4000/rcds
Content-Type: application/json

{
    "doc_id": "66256cb3cf82e1ba244626bc",
    "date": "test", 
    "ors_burs_no": "test", 
    "respo_code": "test", 
    "payee": "test", 
    "uacs_obj_code": "test", 
    "nature_payment": "test", 
    "amount": 200,
    "disbursing_officer": "test"
}

###
DELETE http://localhost:4000/rcds/662572f0430742eec830ffba

###
PATCH http://localhost:4000/rcds/662572c2430742eec830ffa6
Content-Type: application/json

{
    "amount":50
}