GET http://localhost:4000/roles

###
POST http://localhost:4000/roles
Content-Type: application/json

{
    "name": "User"
}

###
DELETE http://localhost:4000/roles/6618eba25b023c442fa2e1eb

###
PATCH http://localhost:4000/roles/6618eba25b023c442fa2e1eb
Content-Type: application/json

{
    "name": "ADOFs"
}