GET http://localhost:4000/schools

###
POST http://localhost:4000/schools
Content-Type: application/json

{
    "name": "Testing ES"
}

###    
DELETE http://localhost:4000/schools/660cd6f4507816b24794b447

###
PATCH http://localhost:4000/schools/661f31c70260a2d33a970464
Content-Type: application/json

{
    "name": "Jaclupan ES",
    "test": "waragud"
}