### Get all the Schools in the database
GET http://localhost:4000/schools

### Get all the Schools in the database
GET http://localhost:4000/schools/Testing ES2 

### Create a new School
POST http://localhost:4000/schools
Content-Type: application/json

{
    "name": "Testing ES3"
}

### Delete a School with the specified ID
DELETE http://localhost:4000/schools/662d55a410d6908cdbe350ce

### Patch School properties
PATCH http://localhost:4000/schools/662d55a410d6908cdbe350ce
Content-Type: application/json

{
    "name": "Jaclupan ES5",
    "test": "waragud"
}