GET http://localhost:4000/users
###

GET http://localhost:4000/users/j.nayon123@gmail.com
###

POST http://localhost:4000/users/validate/
Content-Type: application/json

{
    "email": "j.nayon123@gmail.com",
    "password": "testing"
}
###

POST http://localhost:4000/users
Content-Type: application/json

{
    "fname": "testing",
    "mname": "testing",
    "lname": "testing",
    "username": "testing",
    "email": "j.nayon123@gmail.com",
    "password": "testing",
    "position": "ADAS"
}
###

DELETE http://localhost:4000/users/661f9aa8ebb0be0d4d64bf33

###
PATCH http://localhost:4000/users/661f300c018be135681f3d86
Content-Type: application/json

{
    "name": "bards2",
    "password": "testing nasad",
    "position": "ADOF"
}

###
PATCH http://localhost:4000/users/661f300c018be135681f3d86/school/661f31cd0260a2d33a970467