GET http://localhost:4000/users
###

GET http://localhost:4000/users/j.nayon1234@gmail.com
###

POST http://localhost:4000/users
Content-Type: application/json

{
    "fname": "testing2",
    "mname": "testing2",
    "lname": "testing2",
    "username": "testing2",
    "email": "j.nayon1234@gmail.com",
    "password": "testing nasad",
    "position": "ADAS"
}

###
DELETE http://localhost:4000/users/661e489049025e014b6816d1

###
PATCH http://localhost:4000/users/661e59fec93d4213699ce552
Content-Type: application/json

{
    "name": "bards2",
    "password": "testing nasad",
    "position": "Adas"
}


###
PATCH http://localhost:4000/users/660d2173440a5825bf7fad1d/school
Content-Type: application/json

{
    
    "name": "Jaclupan ES",
    "test": "waragud"
}